// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: chaos.proto

package chaos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChaosService_InjectLatency_FullMethodName = "/chaos.ChaosService/InjectLatency"
	ChaosService_InjectFailure_FullMethodName = "/chaos.ChaosService/InjectFailure"
)

// ChaosServiceClient is the client API for ChaosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChaosServiceClient interface {
	// InjectLatency simulates network latency in a target service.
	InjectLatency(ctx context.Context, in *LatencyRequest, opts ...grpc.CallOption) (*ChaosResponse, error)
	// InjectFailure simulates failures in a target service.
	InjectFailure(ctx context.Context, in *FailureRequest, opts ...grpc.CallOption) (*ChaosResponse, error)
}

type chaosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChaosServiceClient(cc grpc.ClientConnInterface) ChaosServiceClient {
	return &chaosServiceClient{cc}
}

func (c *chaosServiceClient) InjectLatency(ctx context.Context, in *LatencyRequest, opts ...grpc.CallOption) (*ChaosResponse, error) {
	out := new(ChaosResponse)
	err := c.cc.Invoke(ctx, ChaosService_InjectLatency_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosServiceClient) InjectFailure(ctx context.Context, in *FailureRequest, opts ...grpc.CallOption) (*ChaosResponse, error) {
	out := new(ChaosResponse)
	err := c.cc.Invoke(ctx, ChaosService_InjectFailure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChaosServiceServer is the server API for ChaosService service.
// All implementations must embed UnimplementedChaosServiceServer
// for forward compatibility
type ChaosServiceServer interface {
	// InjectLatency simulates network latency in a target service.
	InjectLatency(context.Context, *LatencyRequest) (*ChaosResponse, error)
	// InjectFailure simulates failures in a target service.
	InjectFailure(context.Context, *FailureRequest) (*ChaosResponse, error)
	mustEmbedUnimplementedChaosServiceServer()
}

// UnimplementedChaosServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChaosServiceServer struct {
}

func (UnimplementedChaosServiceServer) InjectLatency(context.Context, *LatencyRequest) (*ChaosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectLatency not implemented")
}
func (UnimplementedChaosServiceServer) InjectFailure(context.Context, *FailureRequest) (*ChaosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectFailure not implemented")
}
func (UnimplementedChaosServiceServer) mustEmbedUnimplementedChaosServiceServer() {}

// UnsafeChaosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChaosServiceServer will
// result in compilation errors.
type UnsafeChaosServiceServer interface {
	mustEmbedUnimplementedChaosServiceServer()
}

func RegisterChaosServiceServer(s grpc.ServiceRegistrar, srv ChaosServiceServer) {
	s.RegisterService(&ChaosService_ServiceDesc, srv)
}

func _ChaosService_InjectLatency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosServiceServer).InjectLatency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChaosService_InjectLatency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosServiceServer).InjectLatency(ctx, req.(*LatencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosService_InjectFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosServiceServer).InjectFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChaosService_InjectFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosServiceServer).InjectFailure(ctx, req.(*FailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChaosService_ServiceDesc is the grpc.ServiceDesc for ChaosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChaosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chaos.ChaosService",
	HandlerType: (*ChaosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InjectLatency",
			Handler:    _ChaosService_InjectLatency_Handler,
		},
		{
			MethodName: "InjectFailure",
			Handler:    _ChaosService_InjectFailure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chaos.proto",
}
