// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: dating.proto

package dating

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwipeRequest_SwipeDirection int32

const (
	SwipeRequest_SWIPE_LEFT  SwipeRequest_SwipeDirection = 0
	SwipeRequest_SWIPE_RIGHT SwipeRequest_SwipeDirection = 1
)

// Enum value maps for SwipeRequest_SwipeDirection.
var (
	SwipeRequest_SwipeDirection_name = map[int32]string{
		0: "SWIPE_LEFT",
		1: "SWIPE_RIGHT",
	}
	SwipeRequest_SwipeDirection_value = map[string]int32{
		"SWIPE_LEFT":  0,
		"SWIPE_RIGHT": 1,
	}
)

func (x SwipeRequest_SwipeDirection) Enum() *SwipeRequest_SwipeDirection {
	p := new(SwipeRequest_SwipeDirection)
	*p = x
	return p
}

func (x SwipeRequest_SwipeDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwipeRequest_SwipeDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_dating_proto_enumTypes[0].Descriptor()
}

func (SwipeRequest_SwipeDirection) Type() protoreflect.EnumType {
	return &file_dating_proto_enumTypes[0]
}

func (x SwipeRequest_SwipeDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SwipeRequest_SwipeDirection.Descriptor instead.
func (SwipeRequest_SwipeDirection) EnumDescriptor() ([]byte, []int) {
	return file_dating_proto_rawDescGZIP(), []int{3, 0}
}

// Request message for getting matches.
type MatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count  int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // Location, age, gender filters would be here
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dating_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dating_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_dating_proto_rawDescGZIP(), []int{0}
}

func (x *MatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MatchRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Message representing a potential match.
type MatchProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username  string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Bio       string   `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Interests []string `protobuf:"bytes,4,rep,name=interests,proto3" json:"interests,omitempty"`
	// A key field: the reason for the match, leveraging XAI data
	MatchReason string `protobuf:"bytes,5,opt,name=match_reason,json=matchReason,proto3" json:"match_reason,omitempty"`
}

func (x *MatchProfile) Reset() {
	*x = MatchProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dating_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchProfile) ProtoMessage() {}

func (x *MatchProfile) ProtoReflect() protoreflect.Message {
	mi := &file_dating_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchProfile.ProtoReflect.Descriptor instead.
func (*MatchProfile) Descriptor() ([]byte, []int) {
	return file_dating_proto_rawDescGZIP(), []int{1}
}

func (x *MatchProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MatchProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MatchProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *MatchProfile) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *MatchProfile) GetMatchReason() string {
	if x != nil {
		return x.MatchReason
	}
	return ""
}

// Response message for getting matches.
type MatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles []*MatchProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dating_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dating_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_dating_proto_rawDescGZIP(), []int{2}
}

func (x *MatchResponse) GetProfiles() []*MatchProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// Request message for recording a swipe.
type SwipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string                      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId string                      `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	Direction    SwipeRequest_SwipeDirection `protobuf:"varint,3,opt,name=direction,proto3,enum=dating.SwipeRequest_SwipeDirection" json:"direction,omitempty"`
}

func (x *SwipeRequest) Reset() {
	*x = SwipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dating_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwipeRequest) ProtoMessage() {}

func (x *SwipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dating_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwipeRequest.ProtoReflect.Descriptor instead.
func (*SwipeRequest) Descriptor() ([]byte, []int) {
	return file_dating_proto_rawDescGZIP(), []int{3}
}

func (x *SwipeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SwipeRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *SwipeRequest) GetDirection() SwipeRequest_SwipeDirection {
	if x != nil {
		return x.Direction
	}
	return SwipeRequest_SWIPE_LEFT
}

// Response message for recording a swipe.
type SwipeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsMatch bool `protobuf:"varint,2,opt,name=is_match,json=isMatch,proto3" json:"is_match,omitempty"` // True if both users swiped right
}

func (x *SwipeResponse) Reset() {
	*x = SwipeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dating_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwipeResponse) ProtoMessage() {}

func (x *SwipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dating_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwipeResponse.ProtoReflect.Descriptor instead.
func (*SwipeResponse) Descriptor() ([]byte, []int) {
	return file_dating_proto_rawDescGZIP(), []int{4}
}

func (x *SwipeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SwipeResponse) GetIsMatch() bool {
	if x != nil {
		return x.IsMatch
	}
	return false
}

var File_dating_proto protoreflect.FileDescriptor

var file_dating_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x64, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x3d, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62,
	0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x6f, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x41,
	0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x30, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x22, 0xc3, 0x01, 0x0a, 0x0c, 0x53, 0x77, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x41, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x64, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x77,
	0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x77, 0x69, 0x70, 0x65,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x0e, 0x53, 0x77, 0x69, 0x70, 0x65, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x57, 0x49, 0x50, 0x45, 0x5f,
	0x4c, 0x45, 0x46, 0x54, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x57, 0x49, 0x50, 0x45, 0x5f,
	0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x01, 0x22, 0x44, 0x0a, 0x0d, 0x53, 0x77, 0x69, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x32, 0x86, 0x01,
	0x0a, 0x0d, 0x44, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x39, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x14, 0x2e,
	0x64, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x53, 0x77, 0x69, 0x70, 0x65, 0x12, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x53, 0x77, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x64, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x77, 0x69, 0x70, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x64, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dating_proto_rawDescOnce sync.Once
	file_dating_proto_rawDescData = file_dating_proto_rawDesc
)

func file_dating_proto_rawDescGZIP() []byte {
	file_dating_proto_rawDescOnce.Do(func() {
		file_dating_proto_rawDescData = protoimpl.X.CompressGZIP(file_dating_proto_rawDescData)
	})
	return file_dating_proto_rawDescData
}

var file_dating_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dating_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dating_proto_goTypes = []interface{}{
	(SwipeRequest_SwipeDirection)(0), // 0: dating.SwipeRequest.SwipeDirection
	(*MatchRequest)(nil),             // 1: dating.MatchRequest
	(*MatchProfile)(nil),             // 2: dating.MatchProfile
	(*MatchResponse)(nil),            // 3: dating.MatchResponse
	(*SwipeRequest)(nil),             // 4: dating.SwipeRequest
	(*SwipeResponse)(nil),            // 5: dating.SwipeResponse
}
var file_dating_proto_depIdxs = []int32{
	2, // 0: dating.MatchResponse.profiles:type_name -> dating.MatchProfile
	0, // 1: dating.SwipeRequest.direction:type_name -> dating.SwipeRequest.SwipeDirection
	1, // 2: dating.DatingService.GetMatches:input_type -> dating.MatchRequest
	4, // 3: dating.DatingService.RecordSwipe:input_type -> dating.SwipeRequest
	3, // 4: dating.DatingService.GetMatches:output_type -> dating.MatchResponse
	5, // 5: dating.DatingService.RecordSwipe:output_type -> dating.SwipeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dating_proto_init() }
func file_dating_proto_init() {
	if File_dating_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dating_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dating_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dating_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dating_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dating_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwipeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dating_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dating_proto_goTypes,
		DependencyIndexes: file_dating_proto_depIdxs,
		EnumInfos:         file_dating_proto_enumTypes,
		MessageInfos:      file_dating_proto_msgTypes,
	}.Build()
	File_dating_proto = out.File
	file_dating_proto_rawDesc = nil
	file_dating_proto_goTypes = nil
	file_dating_proto_depIdxs = nil
}
