import { db } from "./db";
import { adPlacements } from "@shared/schema";

const sampleAds = [
  {
    placementName: "Reels In-Feed #1",
    placementType: "in_feed_reel",
    location: "feed",
    width: 480,
    height: 854,
    width: 480,
    height: 854, // 9:16 aspect ratio for reels
    adType: "in_feed",
    platform: "vids",
    advertiserName: "CashApp",
    adTitle: "Send money instantly - Get $5 bonus",
    adUrl: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800",
    targetUrl: "https://cash.app",
    costPerView: 2,
    cpmRate: "3.00",
    costPerClick: 15,
    frequency: 5,
    isActive: true,
  },
  {
    placementName: "Tube Pre-Roll #1",
    placementType: "pre_roll",
    location: "video_player",
    width: 1280,
    height: 720,
    adType: "pre_roll",
    location: "video_player",
    platform: "tube",
    advertiserName: "Shopify",
    adTitle: "Start your online store today - Free trial",
    adUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
    targetUrl: "https://shopify.com",
    costPerView: 3,
    cpmRate: "5.00",
    costPerClick: 20,
    frequency: 3,
    isActive: true,
  },
  {
    placementName: "Reels In-Feed #2",
    placementType: "in_feed_reel",
    location: "feed",
    width: 480,
    height: 854,
    adType: "in_feed",
    platform: "vids",
    advertiserName: "Fiverr",
    adTitle: "Find freelancers for any project",
    adUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800",
    targetUrl: "https://fiverr.com",
    costPerView: 2,
    cpmRate: "3.00",
    costPerClick: 12,
    frequency: 5,
    isActive: true,
  },
  {
    placementName: "Tube Mid-Roll #1",
    placementType: "mid_roll",
    location: "video_player",
    width: 1280,
    height: 720,
    adType: "mid_roll",
    location: "video_player",
    platform: "tube",
    advertiserName: "Crypto.com",
    adTitle: "Buy Bitcoin, Ethereum & more - 0% fees",
    adUrl: "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=800",
    targetUrl: "https://crypto.com",
    costPerView: 4,
    cpmRate: "6.00",
    costPerClick: 25,
    frequency: 3,
    isActive: true,
  },
  {
    placementName: "Reels In-Feed #3",
    placementType: "in_feed_reel",
    location: "feed",
    width: 480,
    height: 854,
    adType: "in_feed",
    platform: "vids",
    advertiserName: "Skillshare",
    adTitle: "Learn new skills - 2 months FREE",
    adUrl: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800",
    targetUrl: "https://skillshare.com",
    costPerView: 2,
    cpmRate: "3.00",
    costPerClick: 18,
    frequency: 5,
    isActive: true,
  },
  {
    placementName: "Tube Post-Roll #1",
    placementType: "post_roll",
    location: "video_player",
    width: 1280,
    height: 720,
    adType: "post_roll",
    location: "video_player",
    platform: "tube",
    advertiserName: "Webflow",
    adTitle: "Build websites visually - No code needed",
    adUrl: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?w=800",
    targetUrl: "https://webflow.com",
    costPerView: 3,
    cpmRate: "5.00",
    costPerClick: 22,
    frequency: 3,
    isActive: true,
  },
  {
    placementName: "Reels In-Feed #4",
    placementType: "in_feed_reel",
    location: "feed",
    width: 480,
    height: 854,
    adType: "in_feed",
    platform: "vids",
    advertiserName: "Notion",
    adTitle: "All-in-one workspace - Free for personal use",
    adUrl: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800",
    targetUrl: "https://notion.so",
    costPerView: 2,
    cpmRate: "3.00",
    costPerClick: 14,
    frequency: 5,
    isActive: true,
  },
  {
    placementName: "Tube In-Feed #1",
    placementType: "in_feed_tube",
    location: "feed",
    width: 1280,
    height: 720,
    adType: "in_feed",
    platform: "tube",
    advertiserName: "Canva Pro",
    adTitle: "Design like a pro - Try Canva Pro FREE",
    adUrl: "https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=800",
    targetUrl: "https://canva.com/pro",
    costPerView: 2,
    cpmRate: "3.00",
    costPerClick: 16,
    frequency: 5,
    isActive: true,
  },
  {
    placementName: "Global Sidebar #1",
    placementType: "sidebar",
    location: "right_sidebar",
    width: 300,
    height: 250,
    adType: "rotating_sidebar",
    platform: "global",
    advertiserName: "Stripe",
    adTitle: "Accept payments in minutes",
    adDescription: "Built for developers. Loved by businesses. Start accepting payments with Stripe today.",
    adUrl: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=600",
    targetUrl: "https://stripe.com",
    costPerView: 3,
    cpmRate: "5.00",
    costPerClick: 20,
    frequency: 5,
    isActive: true,
  },
  {
    placementName: "Global Sidebar #2",
    placementType: "sidebar",
    location: "right_sidebar",
    width: 300,
    height: 250,
    adType: "rotating_sidebar",
    platform: "global",
    advertiserName: "AWS",
    adTitle: "Cloud computing for everyone",
    adDescription: "Build and scale apps with AWS. Get $300 in free credits to start.",
    adUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600",
    targetUrl: "https://aws.amazon.com",
    costPerView: 4,
    cpmRate: "6.00",
    costPerClick: 25,
    frequency: 5,
    isActive: true,
  },
  {
    placementName: "Global Sidebar #3",
    placementType: "sidebar",
    location: "right_sidebar",
    width: 300,
    height: 250,
    adType: "rotating_sidebar",
    platform: "global",
    advertiserName: "Mailchimp",
    adTitle: "Email marketing made easy",
    adDescription: "Grow your audience with beautiful emails. Free for up to 500 subscribers.",
    adUrl: "https://images.unsplash.com/photo-1557200134-90327ee9fafa?w=600",
    targetUrl: "https://mailchimp.com",
    costPerView: 2,
    cpmRate: "3.00",
    costPerClick: 15,
    frequency: 5,
    isActive: true,
  },
  {
    placementName: "Global Hook Location",
    placementType: "hook",
    location: "hook_bar",
    width: 728,
    height: 90,
    adType: "hook_location",
    platform: "global",
    advertiserName: "Replit",
    adTitle: "Code from anywhere, deploy instantly",
    adDescription: "Build and ship software faster with Replit's cloud development platform.",
    adUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800",
    targetUrl: "https://replit.com",
    costPerView: 5,
    cpmRate: "8.00",
    costPerClick: 30,
    frequency: 10,
    isActive: true,
  },
  {
    placementName: "Tube Banner #1",
    placementType: "banner",
    location: "top_banner",
    width: 970,
    height: 90,
    adType: "banner",
    location: "top_banner",
    platform: "tube",
    advertiserName: "Discord",
    adTitle: "Your place to talk and hang out",
    adDescription: "Join millions in voice, video, and text chat. Download Discord free.",
    adUrl: "https://images.unsplash.com/photo-1614680376739-414d95ff43df?w=1200",
    targetUrl: "https://discord.com",
    costPerView: 1,
    cpmRate: "2.00",
    costPerClick: 8,
    frequency: 1,
    isActive: true,
  },
  {
    placementName: "Reels Banner #1",
    placementType: "banner",
    location: "top_banner",
    width: 970,
    height: 90,
    adType: "banner",
    location: "top_banner",
    platform: "vids",
    advertiserName: "Patreon",
    adTitle: "Get paid for your passion",
    adDescription: "Build a membership business with Patreon. Earn recurring revenue from your fans.",
    adUrl: "https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=1200",
    targetUrl: "https://patreon.com",
    costPerView: 2,
    cpmRate: "3.00",
    costPerClick: 12,
    frequency: 1,
    isActive: true,
  },
];

export async function seedAds() {
  try {
    console.log("🎬 Seeding display ads...");
    
    // Check if ads already exist
    const existingAds = await db.select().from(adPlacements);
    
    if (existingAds.length > 0) {
      console.log(`✅ Already have ${existingAds.length} ads in database`);
      return;
    }
    
    // Insert sample ads
    await db.insert(adPlacements).values(sampleAds as any);
    
    console.log(`✅ Seeded ${sampleAds.length} display ads for monetization`);
  } catch (error) {
    console.error("❌ Error seeding ads:", error);
  }
}
