/**
 * PROFITHACK AI - Agent Video Seeding Service
 * Automatically uploads videos generated by the 200 Agents System to the Founders Account
 * ensuring immediate visibility on the FYP (For You Page)
 */

import { Queue } from 'bullmq';
import Redis from 'ioredis';

// --- Configuration ---
const FOUNDERS_ACCOUNT_ID: string = process.env.FOUNDERS_ACCOUNT_ID || "FOUNDERS_ACCOUNT_UUID_12345";
const VIDEO_PROCESSING_QUEUE_NAME: string = "videoProcessingQueue";

// Initialize Redis connection for BullMQ
const redisConnection = new Redis(process.env.REDIS_URL || "redis://localhost:6379", {
  maxRetriesPerRequest: null,
  enableReadyCheck: false,
});

// Initialize BullMQ queue for video processing
export const videoQueue = new Queue(VIDEO_PROCESSING_QUEUE_NAME, { 
  connection: redisConnection,
  defaultJobOptions: {
    attempts: 3,
    backoff: {
      type: 'exponential',
      delay: 2000,
    },
  },
});

/**
 * Interface for the data payload sent to the video processing service.
 */
interface VideoJobPayload {
  videoUrl: string;
  sourceUserId: string;
  metadata: {
    title: string;
    tags: string[];
    isAgentGenerated: boolean;
    agentName?: string;
    agentType?: string;
  };
}

/**
 * Triggers the video processing pipeline for an agent-generated video,
 * ensuring it is correctly attributed to the Founders Account for seeding.
 * 
 * @param agentVideoUrl The S3/Object Storage URL of the raw video file generated by the agent.
 * @param agentMetadata The title, tags, agent name, and agent type generated by the agent.
 * @returns Promise that resolves when the job is successfully added to the queue.
 */
export async function seedAgentVideo(
  agentVideoUrl: string, 
  agentMetadata: { 
    title: string;
    tags: string[];
    agentName?: string;
    agentType?: string;
  }
): Promise<void> {
  if (!videoQueue) {
    console.error("❌ Video processing queue is not initialized.");
    throw new Error("Queue initialization failure.");
  }

  const jobPayload: VideoJobPayload = {
    videoUrl: agentVideoUrl,
    // CRITICAL: Overwrite the sourceUserId with the Founders Account ID
    // This ensures all agent-generated content appears under the Founders Account
    sourceUserId: FOUNDERS_ACCOUNT_ID, 
    metadata: {
      title: agentMetadata.title,
      // Add special tags for tracking and filtering agent-generated content
      tags: [...agentMetadata.tags, "agent-seed", "founders-content"],
      isAgentGenerated: true,
      agentName: agentMetadata.agentName,
      agentType: agentMetadata.agentType,
    },
  };

  try {
    const job = await videoQueue.add(
      "processAgentVideo", // Job name
      jobPayload,
      { 
        // Prioritize agent-seeded content to ensure the FYP is always fresh
        priority: 1, // High priority (lower number = higher priority)
        removeOnComplete: {
          count: 100, // Keep last 100 completed jobs for debugging
        },
        removeOnFail: {
          count: 50, // Keep last 50 failed jobs for debugging
        },
      }
    );
    
    console.log(`✅ Successfully added agent video job for Founders Account: ${jobPayload.metadata.title}`);
    console.log(`   Job ID: ${job.id}`);
    console.log(`   Agent: ${agentMetadata.agentName || 'Unknown'} (${agentMetadata.agentType || 'Unknown'})`);
    
  } catch (error) {
    console.error("❌ Failed to add agent video job to queue:", error);
    throw error;
  }
}

/**
 * Batch seed multiple agent videos at once (for bulk operations)
 * 
 * @param videos Array of agent video data to seed
 * @returns Promise that resolves when all jobs are successfully added
 */
export async function batchSeedAgentVideos(
  videos: Array<{
    url: string;
    title: string;
    tags: string[];
    agentName?: string;
    agentType?: string;
  }>
): Promise<void> {
  console.log(`📦 Batch seeding ${videos.length} agent videos...`);
  
  const promises = videos.map(video => 
    seedAgentVideo(video.url, {
      title: video.title,
      tags: video.tags,
      agentName: video.agentName,
      agentType: video.agentType,
    })
  );

  try {
    await Promise.all(promises);
    console.log(`✅ Successfully batch seeded ${videos.length} agent videos`);
  } catch (error) {
    console.error(`❌ Failed to batch seed agent videos:`, error);
    throw error;
  }
}

/**
 * Get statistics about agent video seeding
 * 
 * @returns Object containing queue statistics
 */
export async function getAgentVideoQueueStats() {
  const waiting = await videoQueue.getWaitingCount();
  const active = await videoQueue.getActiveCount();
  const completed = await videoQueue.getCompletedCount();
  const failed = await videoQueue.getFailedCount();

  return {
    waiting,
    active,
    completed,
    failed,
    total: waiting + active + completed + failed,
  };
}

// --- Example Usage (Called by the 200 Agents System) ---
/*
// Example of an agent generating a video and calling this function
const agentOutput = {
  url: "s3://profithack-raw/agent-video-20251123.mp4",
  title: "Golang Microservice Tutorial in 60 Seconds",
  tags: ["golang", "microservices", "tutorial", "coding"],
  agentName: "TikTok Viral Machine",
  agentType: "content_creator"
};

// In the 200 Agents System's final step:
await seedAgentVideo(agentOutput.url, {
  title: agentOutput.title,
  tags: agentOutput.tags,
  agentName: agentOutput.agentName,
  agentType: agentOutput.agentType
});

// Batch example:
await batchSeedAgentVideos([
  {
    url: "s3://profithack-raw/video1.mp4",
    title: "Amazing AI Tutorial",
    tags: ["ai", "tutorial"],
    agentName: "AI Educator Bot",
    agentType: "content_creator"
  },
  {
    url: "s3://profithack-raw/video2.mp4",
    title: "Coding Best Practices",
    tags: ["coding", "bestpractices"],
    agentName: "Code Mentor Bot",
    agentType: "content_creator"
  }
]);
*/
