// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: sora.proto

package sora

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SoraService_GenerateVideo_FullMethodName = "/sora.SoraService/GenerateVideo"
)

// SoraServiceClient is the client API for SoraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoraServiceClient interface {
	// GenerateVideo handles the request to generate a video from a text prompt.
	GenerateVideo(ctx context.Context, in *GenerateVideoRequest, opts ...grpc.CallOption) (*GenerateVideoResponse, error)
}

type soraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoraServiceClient(cc grpc.ClientConnInterface) SoraServiceClient {
	return &soraServiceClient{cc}
}

func (c *soraServiceClient) GenerateVideo(ctx context.Context, in *GenerateVideoRequest, opts ...grpc.CallOption) (*GenerateVideoResponse, error) {
	out := new(GenerateVideoResponse)
	err := c.cc.Invoke(ctx, SoraService_GenerateVideo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoraServiceServer is the server API for SoraService service.
// All implementations must embed UnimplementedSoraServiceServer
// for forward compatibility
type SoraServiceServer interface {
	// GenerateVideo handles the request to generate a video from a text prompt.
	GenerateVideo(context.Context, *GenerateVideoRequest) (*GenerateVideoResponse, error)
	mustEmbedUnimplementedSoraServiceServer()
}

// UnimplementedSoraServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSoraServiceServer struct {
}

func (UnimplementedSoraServiceServer) GenerateVideo(context.Context, *GenerateVideoRequest) (*GenerateVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateVideo not implemented")
}
func (UnimplementedSoraServiceServer) mustEmbedUnimplementedSoraServiceServer() {}

// UnsafeSoraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoraServiceServer will
// result in compilation errors.
type UnsafeSoraServiceServer interface {
	mustEmbedUnimplementedSoraServiceServer()
}

func RegisterSoraServiceServer(s grpc.ServiceRegistrar, srv SoraServiceServer) {
	s.RegisterService(&SoraService_ServiceDesc, srv)
}

func _SoraService_GenerateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoraServiceServer).GenerateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SoraService_GenerateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoraServiceServer).GenerateVideo(ctx, req.(*GenerateVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SoraService_ServiceDesc is the grpc.ServiceDesc for SoraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sora.SoraService",
	HandlerType: (*SoraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateVideo",
			Handler:    _SoraService_GenerateVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sora.proto",
}
