// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: xai.proto

package xai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for the XAI service.
type XAIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count           int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ExcludeVideoIds []string `protobuf:"bytes,3,rep,name=exclude_video_ids,json=excludeVideoIds,proto3" json:"exclude_video_ids,omitempty"`
}

func (x *XAIRequest) Reset() {
	*x = XAIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XAIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAIRequest) ProtoMessage() {}

func (x *XAIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAIRequest.ProtoReflect.Descriptor instead.
func (*XAIRequest) Descriptor() ([]byte, []int) {
	return file_xai_proto_rawDescGZIP(), []int{0}
}

func (x *XAIRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *XAIRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *XAIRequest) GetExcludeVideoIds() []string {
	if x != nil {
		return x.ExcludeVideoIds
	}
	return nil
}

// Message representing a single recommended video with its explanation.
type RecommendedVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId     string `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Explanation string `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"` // The "Explainable" part
}

func (x *RecommendedVideo) Reset() {
	*x = RecommendedVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendedVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedVideo) ProtoMessage() {}

func (x *RecommendedVideo) ProtoReflect() protoreflect.Message {
	mi := &file_xai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedVideo.ProtoReflect.Descriptor instead.
func (*RecommendedVideo) Descriptor() ([]byte, []int) {
	return file_xai_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendedVideo) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *RecommendedVideo) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

// Response message for the XAI service.
type XAIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recommendations []*RecommendedVideo `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
}

func (x *XAIResponse) Reset() {
	*x = XAIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XAIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAIResponse) ProtoMessage() {}

func (x *XAIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAIResponse.ProtoReflect.Descriptor instead.
func (*XAIResponse) Descriptor() ([]byte, []int) {
	return file_xai_proto_rawDescGZIP(), []int{2}
}

func (x *XAIResponse) GetRecommendations() []*RecommendedVideo {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_xai_proto protoreflect.FileDescriptor

var file_xai_proto_rawDesc = []byte{
	0x0a, 0x09, 0x78, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x78, 0x61, 0x69,
	0x22, 0x67, 0x0a, 0x0a, 0x58, 0x41, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a,
	0x11, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64,
	0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x73, 0x22, 0x4f, 0x0a, 0x10, 0x52, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x19, 0x0a,
	0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6c,
	0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65,
	0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x0b, 0x58, 0x41,
	0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0f, 0x72, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x78, 0x61, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x64, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x44, 0x0a, 0x0a, 0x58, 0x41,
	0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x2e,
	0x78, 0x61, 0x69, 0x2e, 0x58, 0x41, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x78, 0x61, 0x69, 0x2e, 0x58, 0x41, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x78, 0x61, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_xai_proto_rawDescOnce sync.Once
	file_xai_proto_rawDescData = file_xai_proto_rawDesc
)

func file_xai_proto_rawDescGZIP() []byte {
	file_xai_proto_rawDescOnce.Do(func() {
		file_xai_proto_rawDescData = protoimpl.X.CompressGZIP(file_xai_proto_rawDescData)
	})
	return file_xai_proto_rawDescData
}

var file_xai_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_xai_proto_goTypes = []interface{}{
	(*XAIRequest)(nil),       // 0: xai.XAIRequest
	(*RecommendedVideo)(nil), // 1: xai.RecommendedVideo
	(*XAIResponse)(nil),      // 2: xai.XAIResponse
}
var file_xai_proto_depIdxs = []int32{
	1, // 0: xai.XAIResponse.recommendations:type_name -> xai.RecommendedVideo
	0, // 1: xai.XAIService.GetRecommendation:input_type -> xai.XAIRequest
	2, // 2: xai.XAIService.GetRecommendation:output_type -> xai.XAIResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xai_proto_init() }
func file_xai_proto_init() {
	if File_xai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XAIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommendedVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xai_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XAIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xai_proto_goTypes,
		DependencyIndexes: file_xai_proto_depIdxs,
		MessageInfos:      file_xai_proto_msgTypes,
	}.Build()
	File_xai_proto = out.File
	file_xai_proto_rawDesc = nil
	file_xai_proto_goTypes = nil
	file_xai_proto_depIdxs = nil
}
