// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: xai.proto

package xai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	XAIService_GetRecommendation_FullMethodName = "/xai.XAIService/GetRecommendation"
)

// XAIServiceClient is the client API for XAIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XAIServiceClient interface {
	// GetRecommendation provides a list of video IDs and the explanation for the recommendation.
	GetRecommendation(ctx context.Context, in *XAIRequest, opts ...grpc.CallOption) (*XAIResponse, error)
}

type xAIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXAIServiceClient(cc grpc.ClientConnInterface) XAIServiceClient {
	return &xAIServiceClient{cc}
}

func (c *xAIServiceClient) GetRecommendation(ctx context.Context, in *XAIRequest, opts ...grpc.CallOption) (*XAIResponse, error) {
	out := new(XAIResponse)
	err := c.cc.Invoke(ctx, XAIService_GetRecommendation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XAIServiceServer is the server API for XAIService service.
// All implementations must embed UnimplementedXAIServiceServer
// for forward compatibility
type XAIServiceServer interface {
	// GetRecommendation provides a list of video IDs and the explanation for the recommendation.
	GetRecommendation(context.Context, *XAIRequest) (*XAIResponse, error)
	mustEmbedUnimplementedXAIServiceServer()
}

// UnimplementedXAIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedXAIServiceServer struct {
}

func (UnimplementedXAIServiceServer) GetRecommendation(context.Context, *XAIRequest) (*XAIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendation not implemented")
}
func (UnimplementedXAIServiceServer) mustEmbedUnimplementedXAIServiceServer() {}

// UnsafeXAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XAIServiceServer will
// result in compilation errors.
type UnsafeXAIServiceServer interface {
	mustEmbedUnimplementedXAIServiceServer()
}

func RegisterXAIServiceServer(s grpc.ServiceRegistrar, srv XAIServiceServer) {
	s.RegisterService(&XAIService_ServiceDesc, srv)
}

func _XAIService_GetRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XAIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XAIServiceServer).GetRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XAIService_GetRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XAIServiceServer).GetRecommendation(ctx, req.(*XAIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XAIService_ServiceDesc is the grpc.ServiceDesc for XAIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XAIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xai.XAIService",
	HandlerType: (*XAIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecommendation",
			Handler:    _XAIService_GetRecommendation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xai.proto",
}
