// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: monetization.proto

package monetization

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MonetizationService_SendGift_FullMethodName  = "/monetization.MonetizationService/SendGift"
	MonetizationService_Subscribe_FullMethodName = "/monetization.MonetizationService/Subscribe"
)

// MonetizationServiceClient is the client API for MonetizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonetizationServiceClient interface {
	// SendGift handles the transaction for sending a virtual gift.
	SendGift(ctx context.Context, in *SendGiftRequest, opts ...grpc.CallOption) (*SendGiftResponse, error)
	// Subscribe handles the transaction for a user subscribing to a creator.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
}

type monetizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonetizationServiceClient(cc grpc.ClientConnInterface) MonetizationServiceClient {
	return &monetizationServiceClient{cc}
}

func (c *monetizationServiceClient) SendGift(ctx context.Context, in *SendGiftRequest, opts ...grpc.CallOption) (*SendGiftResponse, error) {
	out := new(SendGiftResponse)
	err := c.cc.Invoke(ctx, MonetizationService_SendGift_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monetizationServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, MonetizationService_Subscribe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonetizationServiceServer is the server API for MonetizationService service.
// All implementations must embed UnimplementedMonetizationServiceServer
// for forward compatibility
type MonetizationServiceServer interface {
	// SendGift handles the transaction for sending a virtual gift.
	SendGift(context.Context, *SendGiftRequest) (*SendGiftResponse, error)
	// Subscribe handles the transaction for a user subscribing to a creator.
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	mustEmbedUnimplementedMonetizationServiceServer()
}

// UnimplementedMonetizationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMonetizationServiceServer struct {
}

func (UnimplementedMonetizationServiceServer) SendGift(context.Context, *SendGiftRequest) (*SendGiftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGift not implemented")
}
func (UnimplementedMonetizationServiceServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedMonetizationServiceServer) mustEmbedUnimplementedMonetizationServiceServer() {}

// UnsafeMonetizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonetizationServiceServer will
// result in compilation errors.
type UnsafeMonetizationServiceServer interface {
	mustEmbedUnimplementedMonetizationServiceServer()
}

func RegisterMonetizationServiceServer(s grpc.ServiceRegistrar, srv MonetizationServiceServer) {
	s.RegisterService(&MonetizationService_ServiceDesc, srv)
}

func _MonetizationService_SendGift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGiftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonetizationServiceServer).SendGift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonetizationService_SendGift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonetizationServiceServer).SendGift(ctx, req.(*SendGiftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonetizationService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonetizationServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonetizationService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonetizationServiceServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonetizationService_ServiceDesc is the grpc.ServiceDesc for MonetizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonetizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monetization.MonetizationService",
	HandlerType: (*MonetizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendGift",
			Handler:    _MonetizationService_SendGift_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _MonetizationService_Subscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monetization.proto",
}
