// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: dating.proto

package dating

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DatingService_GetMatches_FullMethodName  = "/dating.DatingService/GetMatches"
	DatingService_RecordSwipe_FullMethodName = "/dating.DatingService/RecordSwipe"
)

// DatingServiceClient is the client API for DatingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatingServiceClient interface {
	// GetMatches returns a stream of potential matches for the user.
	GetMatches(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
	// RecordSwipe records the user's swipe action.
	RecordSwipe(ctx context.Context, in *SwipeRequest, opts ...grpc.CallOption) (*SwipeResponse, error)
}

type datingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatingServiceClient(cc grpc.ClientConnInterface) DatingServiceClient {
	return &datingServiceClient{cc}
}

func (c *datingServiceClient) GetMatches(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, DatingService_GetMatches_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datingServiceClient) RecordSwipe(ctx context.Context, in *SwipeRequest, opts ...grpc.CallOption) (*SwipeResponse, error) {
	out := new(SwipeResponse)
	err := c.cc.Invoke(ctx, DatingService_RecordSwipe_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatingServiceServer is the server API for DatingService service.
// All implementations must embed UnimplementedDatingServiceServer
// for forward compatibility
type DatingServiceServer interface {
	// GetMatches returns a stream of potential matches for the user.
	GetMatches(context.Context, *MatchRequest) (*MatchResponse, error)
	// RecordSwipe records the user's swipe action.
	RecordSwipe(context.Context, *SwipeRequest) (*SwipeResponse, error)
	mustEmbedUnimplementedDatingServiceServer()
}

// UnimplementedDatingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDatingServiceServer struct {
}

func (UnimplementedDatingServiceServer) GetMatches(context.Context, *MatchRequest) (*MatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatches not implemented")
}
func (UnimplementedDatingServiceServer) RecordSwipe(context.Context, *SwipeRequest) (*SwipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordSwipe not implemented")
}
func (UnimplementedDatingServiceServer) mustEmbedUnimplementedDatingServiceServer() {}

// UnsafeDatingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatingServiceServer will
// result in compilation errors.
type UnsafeDatingServiceServer interface {
	mustEmbedUnimplementedDatingServiceServer()
}

func RegisterDatingServiceServer(s grpc.ServiceRegistrar, srv DatingServiceServer) {
	s.RegisterService(&DatingService_ServiceDesc, srv)
}

func _DatingService_GetMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatingServiceServer).GetMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatingService_GetMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatingServiceServer).GetMatches(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatingService_RecordSwipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatingServiceServer).RecordSwipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatingService_RecordSwipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatingServiceServer).RecordSwipe(ctx, req.(*SwipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatingService_ServiceDesc is the grpc.ServiceDesc for DatingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dating.DatingService",
	HandlerType: (*DatingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatches",
			Handler:    _DatingService_GetMatches_Handler,
		},
		{
			MethodName: "RecordSwipe",
			Handler:    _DatingService_RecordSwipe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dating.proto",
}
